export { ReactComponent as CheckCircleIcon } from "@repo/assets/icon/ic_check_circle.svg";
export { ReactComponent as CloseCircleIcon } from "@repo/assets/icon/ic_close_circle.svg";
export { ReactComponent as DashboardIcon } from "@repo/assets/icon/ic_dashboard.svg";
export { ReactComponent as DownIcon } from "@repo/assets/icon/ic_down.svg";
export { ReactComponent as ExclamationCircleIcon } from "@repo/assets/icon/ic_exclamation_circle.svg";
export { ReactComponent as GreenCheckIcon } from "@repo/assets/icon/ic_green_check.svg";
export { ReactComponent as LeftArrowIcon } from "@repo/assets/icon/ic_left_arrow.svg";
export { ReactComponent as LogoCarInspectionIcon } from "@repo/assets/icon/ic_logo_car_inspection.svg";
export { ReactComponent as LogoutIcon } from "@repo/assets/icon/ic_logout.svg";
export { ReactComponent as PhotoIcon } from "@repo/assets/icon/ic_photo.svg";
export { ReactComponent as RefreshIcon } from "@repo/assets/icon/ic_refresh.svg";
export { ReactComponent as RemarkIcon } from "@repo/assets/icon/ic_remark.svg";
export { ReactComponent as TransmissionIcon } from "@repo/assets/icon/ic_transmission.svg";
export * from "./language";
export * from "./static/icon/resultIcons";
export * from "./static/objectArray";
export * from "./static/queryFilter";
export * from "./static/queryFilterSkeleton";
export * from "./static/tab";
export * from "./static/table/tableHeaderInfos";
