export const COMMON_ERROR_CODE = {
  ALREADY_CANCELED: "ALREADY_CANCELED",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  BAD_REQUEST: "BAD_REQUEST",
  DUPLICATE_SIGNIN_DETECTED: "DUPLICATE_SIGNIN_DETECTED",
  DUPLICATED_SIGNIN_DETECTED: "DUPLICATED_SIGNIN_DETECTED", // TODO: move admin, iot 서버 반영 및 웹에 배포 완료 후 삭제 필요
  EMAIL_EXISTS: "EMAIL_EXISTS",
  EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  INVALID_SIGNIN: "INVALID_SIGNIN",
  NOT_FOUND: "NOT_FOUND",
} as const;

// TODO: Move admin도 code를 보고 API 에러를 정의할 수 있도록 수정 필요
// LINK: https://www.notion.so/coconutsilo/014db9ddc51a4240ba0979e987e2a252?v=f07fd59540e44c2e85c7f112c5a75964&pvs=4

// LINK: https://www.notion.so/coconutsilo/c10f9375bdc644c68cdc9b389a18a153?v=abc121e93604453e84b6aea0822a3f10&pvs=4
export const LOGISTICS_ERROR_CODE = {
  ...COMMON_ERROR_CODE,
  CANNOT_UPDATE: "CANNOT_UPDATE",
  INVALID_PASSWORD: "INVALID_PASSWORD",
} as const;

// LINK: https://www.notion.so/coconutsilo/28539fcbb9c147269f3fccd7a7ad1b1c?v=955a262aef9a4f939df47e8f023ef5a7
export const CAR_ADMIN_ERROR_CODE = {
  ...COMMON_ERROR_CODE,
  ALREADY_ANSWERED: "ALREADY_ANSWERED",
  AUTH_CODE_EXPIRED: "AUTH_CODE_EXPIRED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_AUTH_CODE: "INVALID_AUTH_CODE",
  INVALID_TOKEN: "INVALID_TOKEN",
  NOT_FOUND: "NOT_FOUND",
} as const;

export const CAR_INSPECTION_ERROR_CODE = {
  ...COMMON_ERROR_CODE,
  INVALID_AUTH_CODE: "INVALID_AUTH_CODE",
  INVALID_TOKEN: "INVALID_TOKEN",
} as const;

export const ECOMMERCE_ADMIN_ERROR_CODE = {
  ...COMMON_ERROR_CODE,
} as const;

export const MEMBERSHIP_ADMIN_ERROR_CODE = {
  ...COMMON_ERROR_CODE,
} as const;
