export const COMMON_ERROR_CODE = {
  CANNOT_UPDATE_PASSWORD: "CANNOT_UPDATE_PASSWORD",
  DUPLICATE_SIGNIN_DETECTED: "DUPLICATE_SIGNIN_DETECTED",
  DUPLICATED_SIGNIN_DETECTED: "DUPLICATED_SIGNIN_DETECTED", // TODO: move admin, iot 서버 반영 및 웹에 배포 완료 후 삭제 필요
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  INVALID_TOKEN: "INVALID_TOKEN",
} as const;
