import type { Languages } from "@repo/types";

import { LANGUAGE_LABEL } from "../languageLabel";

export const COMMON_ERROR_MESSAGE = {
  CANNOT_UPDATE_PASSWORD: LANGUAGE_LABEL.IS_NOT_A_CURRENT_PASSWORD, //NOTE: kokkokAdmin 만 문구 달라서 확인 요청 상태
  EMAIL_VALID: LANGUAGE_LABEL.PLEASE_ENTER_A_VALID_EMAIL_ADDRESS,
  FIELD: LANGUAGE_LABEL.THIS_FIELD_IS_MANDATORY,
  MOBILE_VALID: LANGUAGE_LABEL.PLEASE_ENTER_A_VALID_MOBILE_NUMBER,
  PASSWORD_CONFIRM: LANGUAGE_LABEL.PASSWORD_MATCHES,
  PASSWORD_LENGTH: LANGUAGE_LABEL.EIGHT_TWENTY_CHARACTERS,
  PASSWORD_TYPE: LANGUAGE_LABEL.AT_LEAST_2_TYPES_A_Z_A_Z_NUMBERS_SYMBOLS,
  URL_INCORRECT: LANGUAGE_LABEL.PLEASE_ENTER_A_VALID_URL,
  VERSION_INCORRECT: LANGUAGE_LABEL.PLEASE_ENTER_A_VERSION_IN_VALID_FORMAT_0_0_0,
} satisfies Record<string, Languages>;
