import type { CarInspectionLanguages } from "~types";

export const LANGUAGE_LABEL = {
  BACK_TO_INSPECTION_RESULT: "Back to inspection result",
  BAD: "Bad",
  BRAND: "Brand",
  CANCEL: "Cancel",
  CAR_INSPECTION: "Car inspection",
  CAR_TYPE: "Car type",
  CARS_REQUIRE_INSPECTION: "Cars require inspection",
  COLOR: "Color",
  COMPLETE_INSPECTION: "Complete inspection",
  DESCRIBE: "Describe",
  ENGINE_NUMBER: "Engine number",
  ENGINE: "Engine",
  ENTER_THE_ENGINE_NUMBER: "Enter the engine number",
  ENTER_THE_INSPECTION_CODE: "Enter the inspection code",
  ENTER_THE_MILEAGE: "Enter the mileage" as CarInspectionLanguages, // TODO: 문구 확인 필요
  ENTER_THE_MODEL: "Enter the model",
  ENTER_THE_YEAR: "Enter the year",
  EXTERIOR: "Exterior",
  FAILED_TO_COMPLETE_INSPECTION: "Failed to complete inspection.",
  FRAME_ENGINE_NUMBER: "Frame/engine number",
  FRAME_NUMBER: "Frame number",
  FUEL_TYPE: "Fuel type",
  INCORRECT_EMAIL_OR_PASSWORD: "Incorrect email or password.",
  INSPECTED_BY: "Inspected by",
  INSPECTED_DATE: "Inspected date",
  INSPECTION_CODE: "Insepction code",
  INSPECTION_COMPLETED_SUCCESSFULLY: "Inspection completed successfully.",
  INSPECTION_ITEM: "Inspection item",
  INSPECTION_REQUIRED: "Inspection required",
  INTERIOR: "Interior",
  LAST_UPDATED: "Latest updated",
  LIST: "List",
  MILEAGE: "Mileage",
  MODEL_INFORMATION: "Model information",
  MODEL: "Model",
  NO_RESULTS_FOUND: "No results found",
  NO: "No.",
  NORMAL: "Normal",
  PASS: "Pass",
  PLEASE_APPLY_THE_FILTER_TO_SEARCH: "Please apply the filter to search",
  REMARKS: "Remarks",
  RESULT: "Result",
  SAVE: "Save",
  SELECT_THE_OPTION: "Select the option",
  START_INSPECTION: "Start inspection",
  SUPPORT_FILE_PNG_JPEG_JPG: "Support file : png, jpeg, jpg",
  TRANSMISSON: "Transmission",
  UNDERSIDE: "Underside",
  UPLOAD_PHOTO: "Upload photo",
  YEAR: "Year",
  YOU_CAN_UPLOAD_UP_TO_3_FILES_AT_A_TIME:
    "You can upload up to 3 files at a time.",
  YOU_CAN_UPLOAD_UP_TO_3_PHOTOS: "You can upload up to 3 photos.",
} satisfies Record<string, CarInspectionLanguages>;
