name: Common
description: 작업 노션 링크, 개발 개요, 추후 개발 내용, 특이사항을 작성할 때 사용
title: ""
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 개요  
        > 해당 이슈를 생성하게 된 목적과 이유에 대해 작성합니다.

  - type: input
    id: notion
    attributes:
      label: 🔗 작업 Notion 링크
      placeholder: "https://notion.so/..."
    validations:
      required: false

  - type: textarea
    id: work
    attributes:
      label: 💬 작업 내용
      placeholder: "Pull request 제목 및 번호를 적어주세요"
    validations:
      required: false

  - type: textarea
    id: note
    attributes:
      label: ⚠️ 특이사항 (참고)
      placeholder: "공유할 이슈, 제한사항 등"
    validations:
      required: false
