import type { Languages } from "@repo/types";

export const LANGUAGE_LABEL = {
  A_PROBLEM_OCCURRED_WHILE_CALCULATING_THE_ROUTE_SO_THE_ROUTE_CANNOT_BE_DISPLAYED: "A problem occurred while calculating the route, so the route cannot be displayed.",
  APPLY: "Apply",
  APR: "APR",
  AT_LEAST_2_TYPES_A_Z_A_Z_NUMBERS_SYMBOLS: "At least 2 types (A-Z, a-z, numbers, symbols)",
  AUG: "AUG",
  BACKGROUND_COLOR: "Background color",
  BANNER_IMAGE: "Banner image",
  CANCEL: "Cancel",
  CHANGE_PASSWORD: "Change password",
  CHANGES_YOU_MADE_MAY_NOT_BE_SAVED: "Changes you made may not be saved.",
  CLOSE: "Close",
  CONFIRM_PASSWORD: "Confirm password",
  CONFIRM: "Confirm",
  COPIED_THE_MOBILE_NUMBER: "Copied the mobile number.",
  CREATE_A_NEW_PASSWORD: "Create a new password",
  CREATED_DATE: "Created date",
  CURRENT_PASSWORD: "Current password",
  DEC: "DEC",
  DONE: "Done",
  EDIT: "Edit",
  EIGHT_TWENTY_CHARACTERS: "8-20 characters",
  EMAIL: "Email",
  ENTER_CONFIRM_PASSWORD: "Enter confirm password",
  ENTER_THE_EMAIL_OF_THE_ACCOUNT_THAT_YOU_WISH_TO_RESET_THE_PASSWORD_FOR_WE_LL_SEND_YOU_A_VERIFICATION_CODE: "Enter the email of the account that you wish to reset the password for. We'll send you a verification code.",
  ENTER_THE_FIRST_VERSION_NUMBER: "Enter the first version number",
  ENTER_THE_LAST_VERSION_NUMBER: "Enter the last version number",
  ENTER_THE_REVIEW_VERSION_NUMBER: "Enter the review version number",
  EXPIRATION_TIME: "Expiration time",
  EXPORT: "Export",
  FAILED_COPYING_MOBILE_NUMBER_PLEASE_TRY_AGAIN_LATER: "Failed copying mobile number, please try again later.",
  FEB: "FEB",
  FIRST_VERSION: "First version",
  FRI: "Fri",
  FROM: "From",
  GO_HOME: "Go home",
  IS_NOT_A_CURRENT_PASSWORD: "Is not a current password",
  JAN: "JAN",
  JUL: "JUL",
  JUN: "JUN",
  LAST_VERSION: "Last version",
  LATEST_UPDATED: "Latest updated",
  LATITUDE: "Latitude",
  LEAVE_THIS_PAGE: "Leave this page?",
  LEAVE: "Leave",
  LINK_HAS_BEEN_COPIED: "Link has been copied.",
  LINKED: "Linked",
  LONGITUDE: "Longitude",
  MAR: "MAR",
  MAY: "MAY",
  MOBILE_NUMBER_HAS_BEEN_COPIED: "Mobile number has been copied.",
  MON: "Mon",
  NAME: "Name",
  NEW_PASSWORD: "New password",
  NEXT: "Next",
  NO_HISTORY: "No history",
  NO_RESULTS_FOUND: "No results found",
  NOTICE: "Notice",
  NOV: "NOV",
  OCT: "OCT",
  OFF: "Off",
  ON: "On",
  ORDER: "Order",
  OS: "OS",
  PASSWORD_HAS_BEEN_CHANGED: "Password has been changed.",
  PASSWORD_HAS_BEEN_COPIED: "Password has been copied.",
  PASSWORD_HAS_BEEN_RESET: "Password has been reset",
  PASSWORD_MATCHES: "Password matches",
  PASSWORD: "Password",
  PLATFORM_TYPE: "Platform type",
  PLEASE_APPLY_THE_FILTER_TO_SEARCH: "Please apply the filter to search",
  PLEASE_ENTER_A_VALID_EMAIL_ADDRESS: "Please enter a valid email address.",
  PLEASE_ENTER_A_VALID_MOBILE_NUMBER: "Please enter a valid mobile number.",
  PLEASE_ENTER_A_VALID_URL: "Please enter a valid URL.",
  PLEASE_ENTER_THE_VERSION_IN_VALID_FORMAT_0_0_0: "Please enter the version in valid format. (0.0.0)",
  PLEASE_UPLOAD_A_PHOTO_WITH_A_16_9_RATIO_AND_LANDSCAPE_ORIENTATION: "Please upload a photo with a 16:9 ratio and landscape orientation.",
  RANK: "Rank",
  RESET_PASSWORD: "Reset password",
  RESET: "Reset",
  REVIEW_VERSION: "Review version",
  SAT: "Sat",
  SEARCH_BY_PLATE_NUMBER: "Search by plate number",
  SEARCH_DRIVER_NAME: "Search driver name",
  SELECT_THE_DATE: "Select the date",
  SELECTED: "Selected",
  SEP: "SEP",
  SIGN_IN: "Sign in",
  SIGN_OUT: "Sign out",
  STATUS_HAS_BEEN_CHANGED: "Status has been changed.",
  STATUS: "Status",
  SUN: "Sun",
  SUPPORT_FILE_PNG_JPEG_JPG_LIMIT_0_5MB_PER_FILE: "Support file : png, jpeg, jpg (Limit 0.5MB per file)",
  THE_FILE_CANNOT_EXCEED_MORE_THAN_0_5MB: "The file cannot exceed more than 0.5MB.",
  THE_ROUTE_CANNOT_BE_DISPLAYED_BECAUSE_IT_EXCEEDS_2000_KM: "The route cannot be displayed because it exceeds 2,000 km.",
  THIS_FIELD_IS_MANDATORY: "This field is mandatory.",
  THU: "Thu",
  TO: "To",
  TODAY: "Today",
  TUE: "Tue",
  UPLOAD_PHOTO: "Upload photo",
  URL: "URL",
  VERIFICATION_CODE: "Verification code",
  VERIFY: "Verify",
  WED: "Wed",
} satisfies Record<string, Languages>;
