export const size = {
  DEFAULT_NAV_WIDTH: "64px",
  HEADER_HEIGHT: "56px",
  KOKKOK_ADMIN_NAV_WIDTH: "162px",
  KOKKOK_ADMIN_PADDING_TOP_DELETE: "-20px",
  KOKKOK_ADMIN_PADDING_TOP: "20px",
  MAIN_PADDING_BOTTOM: "40px",
  MAIN_PADDING_DELETE: "-40px",
  MAIN_PADDING_SIDE: "40px",
  MAIN_PADDING_TOP: "40px",
  MAIN_PADDING: "40px",
  MOVE_MONITORING_AUTO_REFRESH_TOGGLE_BUTTON_WIDTH: "85px",
  MOVE_MONITORING_LIST_WIDTH: "390px",
  SCROLL_BAR_WIDTH: "8px",
  SCROLL_BAR_HEIGHT: "6px",
  SECTION_MAX_WIDTH: "1660px",
  SECTION_WIDTH: "1440px",
  TABLE_BODY_HEIGHT: "820px",
  TABLE_CELL_HEIGHT: "40px",
  TABLE_HEADER_HEIGHT: "52px",
  TABLE_HEIGHT: "883px",
} as const;

export type SizeType = typeof size;
