#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# echo "Running build to verify..."
# if ! pnpm run build; then
#   echo "Build failed, push aborted."
#   exit 1
# fi

protected_branches=("main" "develop")
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

for branch in "${protected_branches[@]}"; do
  if [ "$current_branch" = "$branch" ]; then
    echo "Pushing directly to the '$current_branch' branch is not allowed. Please create a feature branch and submit a pull request."
    exit 1
  fi
done

exit 0