export const CHUNK_LIST = {
  library: [
    "@babel/plugin-transform-react-jsx",
    "@googlemaps/markerclusterer",
    "@hookform/resolvers",
    "@react-pdf/renderer",
    "@react-pdf+image",
    "@react-pdf+render",
    "@react-pdf+textkit",
    "@react-pdf+layout",
    "@react-pdf+png",
    "@react-pdf+pdfkit",
    "@tanstack/react-query",
    "axios",
    "concurrently",
    "crypto-js",
    "csvtojson",
    "dayjs",
    "dompurify",
    "emotion-reset",
    "env-cmd",
    "i18next",
    "immer",
    "js-cookie",
    "lodash-es",
    "react-dom",
    "react-ga4",
    "react-hook-form",
    "react-i18next",
    "react-loading-skeleton",
    "react-places-autocomplete",
    "react-qr-code",
    "react-router-dom",
    "react-script-hook",
    "socket.io-client",
    "suneditor",
    "suneditor-react",
    "three",
    "typia",
    "use-immer",
    "uuid",
    "xlsx",
    "yup",
    "zustand",
  ],
  packages: [""],
  apps: [""],
  assets: ["assets"],
};

export const CHUNK_PREFIX = {
  library: "__Libraries",
  packages: "__Packages",
  apps: "__Apps",
  assets: "__Assets",
} as const;
