name: Manual Trigger Workflow

on:
  workflow_dispatch: # 수동 실행 이벤트

jobs:
  run-job:
    runs-on: ubuntu-latest # 워크플로를 실행할 환경 설정
    steps:
      # master 또는 develop이 아닌 브랜치일 때 실패 처리
      - name: Check branch condition
        if: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop' }}
        run: |
          echo "::error:: master 또는 develop 브랜치에서만 실행 가능합니다."
          exit 1

      - name: Develop branch trigger
        if: ${{ github.ref == 'refs/heads/develop' }} # 브랜치가 develop일 때 실행
        run: echo "Develop branch workflow triggered by ${{ github.actor }}"

      - name: Master branch trigger
        if: ${{ github.ref == 'refs/heads/master' }} # 브랜치가 master 때 실행
        run: echo "Master branch workflow triggered by ${{ github.actor }}"
