name: Manual Trigger Workflow

on:
  workflow_dispatch: # 수동 실행 이벤트

jobs:
  run-job:
    runs-on: ubuntu-latest # 워크플로를 실행할 환경 설정
    steps:
      - name: Check branch condition
        if: ${{ github.ref != 'refs/heads/develop' }} # 브랜치가 develop이 아닐 때 실행
        run: |
          echo "::error::This workflow can only be triggered from the 'develop' branch."
          exit 1

      # develop 브랜치 조건 만족 시 실행
      - name: Perform tasks
        if: ${{ github.ref == 'refs/heads/develop' }} # 브랜치가 develop일 때 실행
        run: echo "Workflow triggered by ${{ github.actor }}"
