name: Manual Trigger Workflow

on:
  workflow_dispatch: # 수동 실행 이벤트

jobs:
  run-job:
    runs-on: ubuntu-latest # 워크플로를 실행할 환경 설정

    env:
      AUTHORIZED_USERS_IN_MAIN: "JaegyeongCoconut, test" # main branch 배포 권한이 있는 사용자 정의
      AUTHORIZED_USERS_IN_DEVELOP: "test" # develop branch 배포 권한이 있는 사용자 정의

    steps:
      # main 또는 develop이 아닌 브랜치일 때 실패 처리
      - name: Check branch condition
        if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}
        run: |
          echo "::error:: main 또는 develop 브랜치에서만 실행 가능합니다."
          exit 1

      # develop 브랜치에서 실행
      - name: Develop branch authorization check
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          echo "Authorized users for develop branch: $AUTHORIZED_USERS_IN_DEVELOP"
          if [[ ! ",$AUTHORIZED_USERS_IN_DEVELOP," =~ ",${GITHUB_ACTOR}," ]]; then
            echo "::error:: You are not authorized to deploy to the develop branch."
            exit 1
          fi
          echo "Develop branch workflow triggered by ${{ github.actor }}"

        # main 브랜치에서 권한 확인 및 실행
      - name: Main branch authorization check
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "Authorized users for main branch: $AUTHORIZED_USERS_IN_MAIN"
          if [[ ! ",$AUTHORIZED_USERS_IN_MAIN," =~ ",${GITHUB_ACTOR}," ]]; then
            echo "::error:: You are not authorized to deploy to the main branch."
            exit 1
          fi
          echo "Main branch workflow triggered by ${{ github.actor }}"
